server:
  port: 8082
spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
urlBase: "https://v6.exchangerate-api.com/v6/1227cf5d13731ad6c251bc00"
logging:
  level:
    org.springframework: INFO
    com.coralogix: debug
